Remove extra white space at top of wizard.
digitalbazaar/bedrock-vue-wizard pull request #14
Opened 2019-04-10 15:01 UTC by JoshDunnDev

2019-04-15 16:24 UTC, dlongley requested changes
We need to focus this PR on the spacing and get PR #8 finished and merged -- see comment.

2019-04-15 16:24 UTC, dlongley commented on FinishButton.vue
>        this.$emit('finish');
We're already addressing the disabled/blocked issue in PR #8. Let's get that PR fixed up, reviewed again, and merged and remove these changes here. @gannan08 -- that PR needs your attention for changes and then I can review again and merge.

2019-04-18 14:52 UTC, gannan08 commented
@JoshDunnDev Can we rebase this on top of master and squash some of these commits. We have 12 commits for 10 line code changes across two files.

2019-04-18 15:01 UTC, JoshDunnDev commented
> @JoshDunnDev Can we rebase this on top of master and squash some of these commits. We have 12 commits for 10 line code changes across two files.

There is really only 3 commits that I did. I think extra commits got added when it was previously rebased.

2019-04-18 16:52 UTC, closed without merging